### ISSUE TITLE
ADR_001 - Routes:  Correction Required

### ISSUE THREAD

**Issue by shivun-wits** [witseie-elen4010/2022-group-lab-010#52]
Please note the naming conventions in ADR_001:
- Controllers: xxx.controllers.js
- Routes: xxx.routes.js
- Models: xxx.js
- Middleware: xxx.middleware.js

I would also like to request that the naming convention of the above folders be constraint
to only lowercase, and for this amendment to ADR_001 to be approved and added.

As of 63b6dfa436d9e4bea66ad99a9a17a3bf03ef817d, the naming conventions for the
files: handler.js and main.js in the `routes` folder do not conform.

Also the handlers.js could be converted into a specific controller, and thus should be moved
to the `controllers` folder.

**Comment by Mikaeeld** [comment]
Good catch, these files should be renamed to follow convention. I think it might also be worth creating a new ADR to deal with naming specifically and allow it to partially supersed ADR001
